# Generated by Django 5.2.7 on 2025-11-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('ecampus_id', models.CharField(max_length=255)),
                ('cookies', models.TextField()),
            ],
        ),
    ]
