# Generated by Django 5.2.7 on 2025-11-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='ecampus_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
