# Generated by Django 5.2.7 on 2025-10-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_academicgroup_aud_teacher_groupeschedule_lessonday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='brancId',
            field=models.IntegerField(default=1),
        ),
    ]
