# Generated by Django 5.2.7 on 2025-10-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_institute_brancid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='brancId',
            new_name='branchId',
        ),
    ]
