# Generated by Django 5.2.7 on 2025-10-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
