# Generated by Django 5.2.7 on 2025-10-21 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_institute_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('EduLevel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=50)),
                ('AcademicGroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.academicgroup')),
            ],
        ),
        migrations.CreateModel(
            name='LessonDay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('academic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.academicgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('discipline', models.CharField(max_length=255)),
                ('time_begin', models.TimeField()),
                ('time_end', models.TimeField()),
                ('lesson_type', models.CharField(max_length=255)),
                ('pair_number_start', models.IntegerField()),
                ('pair_number_end', models.IntegerField()),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.aud')),
                ('lesson_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.lessonday')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='LessonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.CharField(max_length=10, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.academicgroup')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('InstituteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institute')),
            ],
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='SpecialtyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.specialty'),
        ),
    ]
