# Generated by Django 5.2.7 on 2025-10-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_brancid_institute_branchid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='branchId',
            new_name='BranchId',
        ),
    ]
