# Generated by Django 5.2.7 on 2025-10-27 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_branchid_institute_branchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='lessonday',
            name='academic_group',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_day',
        ),
        migrations.RemoveField(
            model_name='lessongroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='lessongroup',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='pair_number_end',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='pair_number_start',
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(default='2000-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(default=2004, on_delete=django.db.models.deletion.CASCADE, to='main.academicgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='subgroup',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='weekday',
            field=models.CharField(default=2004, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='discipline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room'),
        ),
        migrations.DeleteModel(
            name='GroupeSchedule',
        ),
        migrations.DeleteModel(
            name='LessonDay',
        ),
        migrations.DeleteModel(
            name='LessonGroup',
        ),
        migrations.DeleteModel(
            name='Aud',
        ),
    ]
