# Generated by Django 5.2.7 on 2025-10-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_room_remove_lessonday_academic_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Name',
            field=models.CharField(default='неизвестно', max_length=100),
        ),
    ]
