# Generated by Django 5.2.7 on 2025-10-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_id',
            field=models.IntegerField(default=2004),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_begin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
